# This file was generated by GoReleaser. DO NOT EDIT.
cask "kaktoos" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "1941120b54d93795b03b0545695646a66864922a33a576b5c6f889fd18892ade"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "102dca2e5188f29623192c0ad60905358a63ce9824bf1ab7c123d910c40f0ee0"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a9534cda710b89244cfb673c5277a79d174dbe0acf922b63ec7e5e40d1e5b9ba"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "85d03fb7f20a8a624f6e88f17ba70d77139c304982fad19154f6afeb431ec80a"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Linux_x86_64.tar.gz"
    end
  end

  name "kaktoos"
  desc "Git-native, scenario-based API regression testing CLI powered by OpenAPI"
  homepage "https://kaktoos.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kaktoos"

  # No zap stanza required
end
