# This file was generated by GoReleaser. DO NOT EDIT.
cask "kaktoos" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "590d071cfe3f9dcc8735820c47ee7f2007d47b9dc2cbf2f3b544c53cbf054149"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "401596163ef2c7ef1110b79e689fe631a420a3b0a80f3d5189de6ab3ea36e0fc"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d0a522abcf14356afc7261f3026188b3ad3860f8a01a8bd945eedb3d39c177fc"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "575825a09e56ed7330d07fd348f0e153bfa19d6a509f601f14a3e71433868b9d"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Linux_x86_64.tar.gz"
    end
  end

  name "kaktoos"
  desc "Git-native, scenario-based API regression testing CLI powered by OpenAPI"
  homepage "https://kaktoos.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kaktoos"

  # No zap stanza required
end
