# This file was generated by GoReleaser. DO NOT EDIT.
cask "kaktoos" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "3ff87c3b815f6bdb3a2d5e4d0f3c316f9bbd3625694820d10a8111ac6ef241e0"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7040958c2235d1d75f9307c31ba3fbf5a427d391fe7ddd5140d6e89b497653f5"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "81aac3021841abcc2e9397b28593d25ab2c42a48376080c814fad6f7cb68a2c6"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "75ca43f3207a035fc479df5961a8a38f01fd551117cc0ed30625eb50ed360752"
      url "https://github.com/kaktooslabs/kaktoos/releases/download/v#{version}/kaktoos_Linux_x86_64.tar.gz"
    end
  end

  name "kaktoos"
  desc "Git-native, scenario-based API regression testing CLI powered by OpenAPI"
  homepage "https://kaktoos.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kaktoos"

  # No zap stanza required
end
